name: Check windows cuda

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
#  build-windows-amd64:
#    runs-on: windows-2022
#    steps:
#      - uses: actions/checkout@v4
#        with:
#          submodules: recursive
#
#      - name: Install Rust
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: 1.82.0
#          override: true
#
#      - name: Install dependencies
#        run: |
#          rustup component add clippy rustfmt
#          cargo fetch
#
#      - name: Build
#        run: cargo build --release -vv
#
#      - name: Archive Binaries
#        run: |
#          mkdir artifacts
#          cp target/release/simple.exe artifacts/simple-windows-amd64.exe
#
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: windows-amd64-binary
#          path: artifacts/
  build-windows-amd64-cuda124:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.82.0
          override: true

#      - name: Cache Cargo Dependencies
#        uses: actions/cache@v4
#        with:
#          path: |
#            ~/.cargo/registry
#            ~/.cargo/git
#          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-cargo-
      - name: Install dependencies
        run: |
          rustup component add clippy rustfmt
          cargo fetch

      # CUDA installation steps
#      - name: Restore CUDA installer
#        id: cache-cuda-restore
#        uses: actions/cache/restore@v4
#        with:
#          path: cuda-install.exe
#          key: https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_551.61_windows.exe
#      - name: Conditionally Download CUDA
#        if: steps.cache-cuda-restore.outputs.cache-hit != 'true'
#        run: |
#          $ErrorActionPreference = "Stop"
#          Invoke-WebRequest -Uri "https://developer.download.nvidia.com/compute/cuda/12.4.0/local_installers/cuda_12.4.0_551.61_windows.exe" -OutFile "cuda-install.exe"
#      - name: Cache CUDA installer
#        if: steps.cache-cuda-restore.outputs.cache-hit != 'true'
#        id: cache-cuda-save
#        uses: actions/cache/save@v4
#        with:
#          path: cuda-install.exe
#          key: ${{ steps.cache-cuda-restore.outputs.cache-primary-key }}
#      - name: Install CUDA
#        run: |
#          $subpackages = @("cudart", "nvcc", "cublas", "cublas_dev") | foreach-object {"${_}_12.4"}
#          Start-Process "cuda-install.exe" -ArgumentList (@("-s") + $subpackages) -NoNewWindow -Wait
#      - name: Verify CUDA
#        run: |
#          & (resolve-path "c:\Program Files\NVIDIA*\CUDA\v*\bin\nvcc.exe")[0] --version
#          $cudaPath=((resolve-path "c:\Program Files\NVIDIA*\CUDA\v*\bin\nvcc.exe")[0].path | split-path | split-path)
#          $cudaVer=($cudaPath | split-path -leaf ) -replace 'v(\d+).(\d+)', '$1_$2'
#
#          echo "Resolved CUDA_PATH: $cudaPath"
#          echo "Cuda Version: $cudaVer"
#          echo "$cudaPath\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
#          echo "CUDA_PATH=$cudaPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#          echo "CUDA_PATH_V${cudaVer}=$cudaPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#          echo "CUDA_PATH_VX_Y=CUDA_PATH_V${cudaVer}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
#      - name: DEBUG CUDA
#        run: |
#
#          echo "CUDA_PATH: $CUDA_PATH"
#          echo "PATH:"
#          echo $env:PATH -split ";"
#          echo "CUDA_PATH_VX_Y: $CUDA_PATH_VX_Y"
#          echo ""
#          echo "Listing contents of CUDA directories..."
#
#          echo "Cuda directory:"
#          ls "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\*"
#
#          echo "Bin directory:"
#          ls "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v*\bin\*"
#
#          echo "Include directory:"
#          ls "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v*\include\*"
#
#          echo "Lib directory:"
#          ls "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v*\lib\x64\*"
      - name: Install Cuda Toolkit 12.4
        run: |
          mkdir -p "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4"
          choco install unzip -y
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cudart/windows-x86_64/cuda_cudart-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvcc/windows-x86_64/cuda_nvcc-windows-x86_64-12.4.131-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvrtc/windows-x86_64/cuda_nvrtc-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/libcublas/windows-x86_64/libcublas-windows-x86_64-12.4.5.8-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvtx/windows-x86_64/cuda_nvtx-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_profiler_api/windows-x86_64/cuda_profiler_api-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/visual_studio_integration/windows-x86_64/visual_studio_integration-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvprof/windows-x86_64/cuda_nvprof-windows-x86_64-12.4.127-archive.zip"
          curl -O "https://developer.download.nvidia.com/compute/cuda/redist/cuda_cccl/windows-x86_64/cuda_cccl-windows-x86_64-12.4.127-archive.zip"
          unzip '*.zip' -d "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4"
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_cudart-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_nvcc-windows-x86_64-12.4.131-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_nvrtc-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libcublas-windows-x86_64-12.4.5.8-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_nvtx-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_profiler_api-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\visual_studio_integration-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_nvprof-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          xcopy "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\cuda_cccl-windows-x86_64-12.4.127-archive\*" "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" /E /I /H /Y
          echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\libnvvp" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          echo "CUDA_PATH_V12_4=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-12.4-cuda

      - name: Install Ninja
        id: install_ninja
        run: |
          choco install ninja
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd llama-cpp-sys-2/llama.cpp
          echo "Current Directory: %CD%"
          cmake -S . -B build -G "Ninja Multi-Config" -DLLAMA_BUILD_SERVER=OFF -DGGML_CUDA=ON -DLLAMA_BUILD_TESTS=OFF -BLLAMA_BUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF
          set /A NINJA_JOBS=%NUMBER_OF_PROCESSORS%-1
          cmake --build build --config Release -j %NINJA_JOBS% -t ggml
          cmake --build build --config Release
          dir build\bin\Release\

#          cargo build --release --features cuda -vv

      - name: Archive Binaries
        run: |
          mkdir artifacts
          cp target/release/simple.exe artifacts/simple-windows-amd64-cuda124.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-amd64-cuda124-binary
          path: artifacts/